name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: gmzwinge/hello-world-composite-action@v4
    - uses: gmzwinge/hello-world-composite-action@v2.0.1
