name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  reusable-workflow:
    uses: GMZwinge/hello-world-composite-action/.github/workflows/workflow.yml@v3.0.1

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: GMZwinge/hello-world-composite-action/.github/actions/action@v3.0.1
    - uses: GMZwinge/hello-world-composite-action/.github/actions/action@v3.0.1
