name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  reusable_workflow:
    uses: "GMZwinge/hello-world-composite-action/.github/workflows/my-workflow.yml@v1.0.8"

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: GMZwinge/hello-world-composite-action/.github/actions/my-action@v1.0.8
