name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  reusable_workflow:
    uses: "GMZwinge/hello-world-composite-action/.github/workflows/my-workflow.yml@v1.0.8"

  build:

    runs-on: ubuntu-latest

    steps:
    # According to [Never change version precision of actions chosen by users](https://github.com/dependabot/dependabot-core/pull/5891),
    # dependabot should not change the version precision. Does it also apply to the version comment
    # when using a commit id instead? It may be better to use the patch version to get security updates,
    # but at least dependabot should update both version comments, not leave the major version comment
    # referring to an old major version that doesn't match the commit id.
    # Dependabot updates those to:
    # uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 #v4.1.0
    # uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 #v3
    # which is find for the commit id, but not the major semver version comment.
    # The commit id are:
    #  v4.1.0: 8ade135a41bc03ea155e62e844d188df1ea18608
    #  v4    : 8ade135a41bc03ea155e62e844d188df1ea18608
    #  v4.0.0: 3df4ab11eba7bda6032a0b82a6bb43b11571feac
    # So it seems that the major version tags are moved to the latest patch version.
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
    - uses: GMZwinge/hello-world-composite-action/.github/actions/my-action@v1.0.8
    - uses: GMZwinge/hello-world-composite-action/.github/actions/my-action@v1.0.8
