name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  reusable_workflow:
    uses: "GMZwinge/hello-world-composite-action/.github/workflows/my-workflow.yml@v1.0.8"

  build:

    runs-on: ubuntu-latest

    steps:
    # According to [Never change version precision of actions chosen by users](https://github.com/dependabot/dependabot-core/pull/5891),
    # dependabot should not change the version precision. Does it also apply to the version comment
    # when using a commit id instead? It may be better to use the patch version to get security updates,
    # but at least dependabot should update both version comments, not leave the major version comment
    # referring to an old major version that doesn't match the commit id.
    # Dependabot updates those to:
    # uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 #v4.1.0
    # uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 #v3
    # which is find for the commit id, but not the major semver version comment.
    # The commit id are:
    #  v4.1.0: 8ade135a41bc03ea155e62e844d188df1ea18608
    #  v4    : 8ade135a41bc03ea155e62e844d188df1ea18608
    #  v4.0.0: 3df4ab11eba7bda6032a0b82a6bb43b11571feac
    # So it seems that the major version tags are moved to the latest patch version.
    # TODO: should create a ticket for this, similar to https://github.com/dependabot/dependabot-core/pull/5891
    # possibly titled something like: Change comment version precision of actions chosen by users.
    # In this case, Dependabot updates both the commit id to 8ade135a41bc03ea155e62e844d188df1ea18608
    # and the version comment to v4.1.0.
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b #v4.1.5
    # In this case, Dependabot updates the commit id to 8ade135a41bc03ea155e62e844d188df1ea18608
    # but not the version comment, even though the version in the comment also has that commit id.
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b #v3
    # What if the commit id and version comment don't match. In both cases, it updates the commit id\
    # to 8ade135a41bc03ea155e62e844d188df1ea18608, but it does not update the version comment.
    # This is a problem: if the version tag is moved, the version comment will no longer be updated
    # until is is manually updated to match the latest patch version for the commit id.
    # It looks like this is a known issue. Searching open issues for [action comment version ](https://github.com/dependabot/dependabot-core/issues?q=is%3Aissue+is%3Aopen+action+comment+version+),
    # found:
    # - [Dependabot doesn't always update version comments for hash-pinned actions/checkout@v3 to @v4](https://github.com/dependabot/dependabot-core/issues/8011).
    # - [Version comment in SHA-pinned github actions is not updated if it's incorrect](https://github.com/dependabot/dependabot-core/issues/7912)
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b #v3.5.3
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b #v3.6.0
    # This is ok.
    - uses: GMZwinge/hello-world-composite-action/.github/actions/my-action@v1.0.8
    - uses: GMZwinge/hello-world-composite-action/.github/actions/my-action@v1.0.8
